# MQTT服务器配置文件
# MQTT Server Configuration

# MQTT服务器连接配置
mqtt_server:
  # MQTT服务器地址 - 使用公共的EMQX服务器
  host: "172.31.232.152"
  # MQTT服务器端口
  port: 1883
  # 连接超时时间(秒)
  keepalive: 60
  # 客户端ID前缀
  client_id_prefix: "vda5050_tcp_server"
  
# MQTT认证配置
mqtt_auth:
  # 用户名 (可选，设置为null表示不使用认证)
  username: null
  # 密码 (可选，设置为null表示不使用认证) 
  password: null
  
# MQTT连接选项
mqtt_options:
  # 自动重连
  auto_reconnect: true
  # 最大重连间隔(秒)
  max_reconnect_delay: 60
  # 初始重连间隔(秒)
  initial_reconnect_delay: 1
  # 清除会话
  clean_session: true
  # QoS等级 (0, 1, 2)
  qos_level: 1

# AGV配置 (从server_config.json合并)
agv:
  # AGV IP地址
  ip: "192.168.1.100"
  # 制造商名称
  manufacturer: "Demo_Manufacturer"
  # 序列号
  serial_number: "AGV_001"
  # 车辆名称
  vehicle_name: "TestAGV"

# TCP端口配置 (从server_config.json合并)
tcp_ports:
  # 状态报告端口
  state_reporting: 19301
  # 命令控制端口
  command_control:
    # 重定位端口
    relocation: 19205
    # 移动控制端口
    movement: 19206
    # 权限控制端口
    authority: 19207
    # 安全端口
    safety: 19210
  # 动作类型配置
  action_types:
    pick:
      port: 19206
      message_type: 3066
    drop:
      port: 19206
      message_type: 3066
    startPause:
      port: 19206
      message_type: 3002
    stopPause:
      port: 19206
      message_type: 3001
    cancelOrder:
      port: 19206
      message_type: 3003
    reloc:
      port: 19205
      message_type: 2002
    cancelReloc:
      port: 19205
      message_type: 2004
    clearErrors:
      port: 19207
      message_type: 4009
    rotateLoad:
      port: 19206
      message_type: 3057
    softEmc:
      port: 19210
      message_type: 6004
    turn:
      port: 19206
      message_type: 3056
    translate:
      port: 19206
      message_type: 3055
    grabAuthority:
      port: 19207
      message_type: 4005
    releaseAuthority:
      port: 19207
      message_type: 4006

# VDA5050主题配置 (符合VDA5050标准格式)
vda5050_topics:
  # 主题前缀
  topic_prefix: "uagv/v2"
  # 订单主题模式 - {manufacturer}/{serial_number}将被替换为实际值
  order_topic_pattern: "uagv/v2/{manufacturer}/{serial_number}/order"
  # 即时动作主题模式
  instant_actions_topic_pattern: "uagv/v2/{manufacturer}/{serial_number}/instantActions"
  # 状态主题模式  
  state_topic_pattern: "uagv/v2/{manufacturer}/{serial_number}/state"
  # 可视化主题模式
  visualization_topic_pattern: "uagv/v2/{manufacturer}/{serial_number}/visualization"
  # 连接主题模式
  connection_topic_pattern: "uagv/v2/{manufacturer}/{serial_number}/connection"
  # 产品说明书主题模式
  factsheet_topic_pattern: "uagv/v2/{manufacturer}/{serial_number}/factsheet"
  
# MQTT消息配置
message_config:
  # 消息保留
  retain: false
  # 最大消息大小(字节)
  max_message_size: 1048576
  # 消息编码
  encoding: "utf-8"

# 服务器配置 (从server_config.json合并)
server:
  # 日志级别
  log_level: "INFO"
  # 日志文件路径
  log_file: "logs/vda5050_server.log"
  # 心跳间隔(秒)
  heartbeat_interval: 30
  # 连接超时时间(秒)
  connection_timeout: 60
  
# 日志配置
logging:
  # 是否启用MQTT日志
  enable_mqtt_logging: true
  # MQTT日志级别 (DEBUG, INFO, WARNING, ERROR)
  mqtt_log_level: "INFO"
  # 是否记录MQTT原始消息
  log_raw_messages: false

# 高级配置
advanced:
  # 消息队列最大长度
  max_queue_length: 1000
  # 处理线程数量
  processing_threads: 4
  # 消息处理超时时间(秒)
  message_timeout: 30 